### ISSUE TITLE
HTML elements in child nodes only usable when holding down mouse click

### ISSUE THREAD

**Issue by theshirokumacoder** [kesha-antonov/jstree-rails-4#2]
Hi there, I was able to get the tree to show but the main issue is when i add a select box html element to a child node, i'm unable to select an option from that box unless i hold down on the mouse and click. Please advise. 

     ```
                    <div id="tree">
                              <li> Parent Node
                                   <ul>
                                    <li> 
                                     <select>
                                        <option value="volvo">Volvo</option>
                                        <option value="saab">Saab</option>
                                        <option value="mercedes">Mercedes</option>
                                        <option value="audi">Audi</option>
                                    </select>
                                   </li>
                                 </ul>
                              </li>
                         </div>

```
 
<script>            
  $(document).ready(function() {

     $('#tree').jstree({
        "plugins": ["themes", "html_data", "wholerow", "ui"],
     });
</script>

```

**Comment by kesha-antonov** [comment]
Hello @TheWolfCoder 

You should ask your question here https://github.com/vakata/jstree
This package just copies assets to your project
