### ISSUE TITLE
Seems to fail with rails 5.1

### ISSUE THREAD

**Issue by arojoal** [kesha-antonov/jstree-rails-4#3]
have you tested this gem under rails 5.1.1?

**Comment by kesha-antonov** [comment]
@arojoal Hello!
No. Feel free to submit PR

**Comment by kesha-antonov** [comment]
What errors to do you experience? Maybe I can help

**Comment by pbelouin-mpiwg** [comment]
hey seems to work fine for me! Thanks for the great plugin btw!

**Comment by kesha-antonov** [comment]
✌️ @pbelouin-mpiwg
