### ISSUE TITLE
No route matches [GET] "/assets/32px.png"

### ISSUE THREAD

**Issue by Pepan** [kesha-antonov/jstree-rails-4#5]
Hallo!

there was change from version 3.3.4 to 3.3.8 in defaults.css for example in route to background

### 3.3.4
...gems/ruby-2.6.2/gems/jstree-rails-4-3.3.4/vendor/assets/stylesheets/jstree-default.scss:514
```
.jstree-default > .jstree-container-ul .jstree-loading > .jstree-ocl {
  background: image-url("default/throbber.gif") center center no-repeat;
}
```
### 3.3.8
...gems/ruby-2.6.2/gems/jstree-rails-4-3.3.8/vendor/assets/stylesheets/jstree-default.scss:517
```
.jstree-default > .jstree-container-ul .jstree-loading > .jstree-ocl {
  background: url("throbber.gif") center center no-repeat;
}
```

causing error

Rack app error handling request { GET /assets/32px.png }
#<ActionController::RoutingError: No route matches [GET] "/assets/32px.png">

-----
I got it during system test ...

**Comment by kesha-antonov** [comment]
Hey!
Nice catch

Seems like we forgot to upgrade script that copying assets https://github.com/kesha-antonov/jstree-rails-4/blob/1a6d4c8cadfe70eaa2909ee3724756b015763496/lib/jstree-rails-4/source_file.rb#L15

**Comment by kesha-antonov** [comment]
@Pepan Can you make PR with fixed script?

**Comment by kesha-antonov** [comment]
Fixed by PR https://github.com/kesha-antonov/jstree-rails-4/pull/6
